### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by nooobcoder** [rohid-dev/code-to-img#1]
Add docker support for self hosted deployments.

**Comment by nooobcoder** [comment]
@rohidisdev I have created a [PR ](https://github.com/rohidisdev/code-to-img/pull/3)from the [`docker`](https://github.com/nooobcoder/code-to-img/tree/docker) branch. 
Please let me know if there are enhancements/corrections to be made,

Regards,
Ankur Paul (@nooobcoder)

**Comment by iam-rohid** [comment]
Hi @nooobcoder 👋
I just merged your code. Thank you so much for your contribution 😎
