### ISSUE TITLE
If the spacing is chosen small, the watermark is very close to the window

### ISSUE THREAD

**Issue by HereOrCode** [rohid-dev/code-to-img#2]
This product is great, I love it so much!

There is a small problem at the moment.

If the spacing is chosen small, the watermark is very close to the window

![CleanShot 2022-05-15 at 11 33 03@2x](https://user-images.githubusercontent.com/83153991/168455981-537128bf-2511-4bc2-9afc-cf1833ccb348.png)

**Comment by iam-rohid** [comment]
I just noticed it. Thanks for letting me know that. 
Should I just push the watermark to the edge a bit more or do you have any other idea how we can solve this issue?

**Comment by HereOrCode** [comment]
Increase the spacing of the minimum(small) size a little bit.😁

I tried to change the value of bottom and it solved the problem, 
I still think we should increase the space a little

![CleanShot 2022-05-15 at 17 49 49@2x](https://user-images.githubusercontent.com/83153991/168466883-d84b4824-34bf-40e7-8d9a-85f3b9e92bf0.png)

**Comment by iam-rohid** [comment]
@code4you2021  That's exactly what I just did 😃
