### ISSUE TITLE
Language CheckBox have a bug？

### ISSUE THREAD

**Issue by RSS1102** [rohid-dev/code-to-img#6]
Unable to display all options in checkBox correctly.
![image](https://user-images.githubusercontent.com/81673017/169181695-fabe50d2-9826-4d6f-8c94-8f2746e30f4c.png)

**Comment by RSS1102** [comment]
This seems to be due to the color of the text

**Comment by iam-rohid** [comment]
Thanks for reporting it. I didn't try this application on windows. On a mac, it works fine. I'm planning to add a custom dropdown. This issue will be resolved after that

**Comment by iam-rohid** [comment]
This issue is fixed now. Added custom select box
